### PR TITLE
remove noalpha support, more script fixes

### PR DESCRIPTION
**Pull request by igorko**
Two things remain:
1. scripts should get image path from animation file(png and txt names do not always match)
2. This will automatically fix issue n2: windows script is unable to extract png path from animation path

### CODE REVIEW

**Comment by igorko** [comment]
@stefanbeller Can you implement 1. inside python script? So it will accept only animation file, parse it and get png location

**Comment by stefanbeller** [comment]
That shozld be doable. Will do tonight.
On Aug 6, 2015 7:53 AM, "Igor Paliychuk" notifications@github.com wrote:

@stefanbeller https://github.com/stefanbeller Can you implement 1. inside
python script? So it will accept only animation file, parse it and get png
location

**Comment by igorko** [comment]
@stefanbeller Merge this PR first ;)

**Comment by igorko** [comment]
Also note about parsing animation file to get png. I'd suggest print warning if png not found (like: png not found, probably it is located in different mod), and not throw error when trying to read missing png

**Pull request merged**
